# doc: https://herdr.dev/
# ref: `herdr --default-config`

onboarding = false

[keys]
prefix = "ctrl+q"
copy_mode = "prefix+["

new_workspace      = "prefix+shift+c"
next_workspace     = "prefix+shift+j"
previous_workspace = "prefix+shift+k"

