FROM docker.io/library/ubuntu:latest AS base

ARG USERNAME=ykyki
ARG PASSWORD=hogehoge

RUN apt-get update \
    && apt-get install -y git make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

USER ${USERNAME}
WORKDIR /home/${USERNAME}/dotfiles24

CMD ["/bin/bash"]