abbrevs:

  - name: awk '{print $1}'
    abbr: '.1'
    snippet: awk '{print $1}'

  - name: git push (force safely)
    abbr: -f
    snippet: --force-with-lease --force-if-includes
    global: true
    context: '^git push\s'

  - name: terraform
    abbr: tf
    snippet: terraform
    if: (( ${+commands[terraform]} )) # available if terraform is installed

  - name: kubectl
    abbr: k
    snippet: kubectl
    if: (( ${+commands[kubectl]} ))

