abbrevs:

  - name: awk '{print $1}'
    abbr: '.1'
    snippet: awk '{print $1}'

  - name: git push (force safely)
    abbr: -f
    snippet: --force-with-lease --force-if-includes
    global: true
    context: '^git push\s'

  - name: docker
    abbr: do
    snippet: docker
    if: (( ${+commands[docker]} ))

  - name: docker compose
    abbr: co
    snippet: compose
    if: (( ${+commands[docker]} ))
    global: true
    context: '^docker\s'

  - name: podman
    abbr: po
    snippet: podman
    if: (( ${+commands[podman]} ))

  - name: kubectl
    abbr: ku
    snippet: kubectl
    if: (( ${+commands[kubectl]} ))

  - name: terraform
    abbr: tf
    snippet: terraform
    if: (( ${+commands[terraform]} ))

