FROM docker.io/library/ubuntu:latest AS base

ARG USERNAME=ykyki
ARG PASSWORD=hogehoge

RUN apt-get update \
    && apt-get install -y make sudo curl locales gcc \
        zsh git vim neovim \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*


RUN sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
    && locale-gen

# RUN chsh -s /bin/zsh

RUN useradd -m -r -G sudo -s /bin/zsh ${USERNAME}
RUN echo "root:${PASSWORD}" | chpasswd
RUN echo "${USERNAME}:${PASSWORD}" | chpasswd
RUN echo '%sudo ALL=(ALL) ALL' | EDITOR='tee -a' visudo

USER ${USERNAME}

RUN echo 'export LANG=en_US.UTF-8' >> ~/.zshrc && \
    echo 'export LC_ALL=en_US.UTF-8' >> ~/.zshrc && \
    echo 'PROMPT="%n@%m:%~%# "' >> ~/.zshrc

WORKDIR /home/${USERNAME}

CMD ["/bin/zsh"]

