FROM docker.io/library/ubuntu:latest AS base

RUN apt-get update \
    && apt-get install -y git make \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workdir/dotfiles

RUN git clone https://github.com/ykyki/dotfiles24.git ./

CMD ["/bin/bash"]